### ISSUE TITLE
Attribute name undefined

### ISSUE THREAD

**Issue by FabriceCastel** [akka/akka-quickstart-scala.g8#2]
Can't get this working. Breaks with the following error.

```
Exiting due to error in the template
File: /var/....../src/main/g8/build.sbt, context [anonymous] 9:14 internal error:
org.stringtemplate.v4.compiler.STException: context [anonymous] 9:14 attribute name isn't defined
```

**Comment by ktoso** [comment]
While you're doing what?

**Comment by FabriceCastel** [comment]
`sbt new akka/akka-scala-seed.g8`

Full trace:

```
Feb 15, 18:57 ~/P/L/Akka Concurrency ∆ sbt new akka/akka-scala-seed.g8
[info] Set current project to akka-concurrency (in build file:/Users/fab/Projects/Learning/Akka%20Concurrency/)
[info] Resolving com.github.scopt#scopt_2.10;3.5.0 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt-giter8-resolver/sbt-giter8-resolver_2.10/0.1.0/sbt-giter8-resolver_2.10-0.1.0.jar ...
[info] 	[SUCCESSFUL ] org.scala-sbt.sbt-giter8-resolver#sbt-giter8-resolver_2.10;0.1.0!sbt-giter8-resolver_2.10.jar (218ms)
[info] downloading https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8_2.10/0.7.1/giter8_2.10-0.7.1.jar ...
[info] 	[SUCCESSFUL ] org.foundweekends.giter8#giter8_2.10;0.7.1!giter8_2.10.jar (901ms)
[info] downloading https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-lib_2.10/0.7.1/giter8-lib_2.10-0.7.1.jar ...
[info] 	[SUCCESSFUL ] org.foundweekends.giter8#giter8-lib_2.10;0.7.1!giter8-lib_2.10.jar (1469ms)
[info] downloading https://repo1.maven.org/maven2/com/github/scopt/scopt_2.10/3.5.0/scopt_2.10-3.5.0.jar ...
[info] 	[SUCCESSFUL ] com.github.scopt#scopt_2.10;3.5.0!scopt_2.10.jar (607ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/scalasti_2.10/2.0.0/scalasti_2.10-2.0.0.jar ...
[info] 	[SUCCESSFUL ] org.clapper#scalasti_2.10;2.0.0!scalasti_2.10.jar (1145ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.pgm/3.7.0.201502260915-r/org.eclipse.jgit.pgm-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit.pgm;3.7.0.201502260915-r!org.eclipse.jgit.pgm.jar (1806ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-archiver/2.7.1/plexus-archiver-2.7.1.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-archiver;2.7.1!plexus-archiver.jar (1415ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/grizzled-scala_2.10/1.2/grizzled-scala_2.10-1.2.jar ...
[info] 	[SUCCESSFUL ] org.clapper#grizzled-scala_2.10;1.2!grizzled-scala_2.10.jar (2926ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/classutil_2.10/1.0.5/classutil_2.10-1.0.5.jar ...
[info] 	[SUCCESSFUL ] org.clapper#classutil_2.10;1.0.5!classutil_2.10.jar (1064ms)
[info] downloading https://repo1.maven.org/maven2/org/antlr/ST4/4.0.8/ST4-4.0.8.jar ...
[info] 	[SUCCESSFUL ] org.antlr#ST4;4.0.8!ST4.jar (1403ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-async_2.10/0.9.1/scala-async_2.10-0.9.1.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang.modules#scala-async_2.10;0.9.1!scala-async_2.10.jar(bundle) (2129ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.2/asm-5.0.2.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm;5.0.2!asm.jar (977ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.0.2/asm-commons-5.0.2.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-commons;5.0.2!asm-commons.jar (1224ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-util/5.0.2/asm-util-5.0.2.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-util;5.0.2!asm-util.jar (1821ms)
[info] downloading https://repo1.maven.org/maven2/org/clapper/grizzled-slf4j_2.10/1.0.2/grizzled-slf4j_2.10-1.0.2.jar ...
[info] 	[SUCCESSFUL ] org.clapper#grizzled-slf4j_2.10;1.0.2!grizzled-slf4j_2.10.jar (1767ms)
[info] downloading https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.2/asm-tree-5.0.2.jar ...
[info] 	[SUCCESSFUL ] org.ow2.asm#asm-tree;5.0.2!asm-tree.jar (1824ms)
[info] downloading https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar ...
[info] 	[SUCCESSFUL ] org.antlr#antlr-runtime;3.5.2!antlr-runtime.jar (1653ms)
[info] downloading https://repo1.maven.org/maven2/args4j/args4j/2.0.12/args4j-2.0.12.jar ...
[info] 	[SUCCESSFUL ] args4j#args4j;2.0.12!args4j.jar (954ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.6/commons-compress-1.6.jar ...
[info] 	[SUCCESSFUL ] org.apache.commons#commons-compress;1.6!commons-compress.jar (3213ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.archive/3.7.0.201502260915-r/org.eclipse.jgit.archive-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit.archive;3.7.0.201502260915-r!org.eclipse.jgit.archive.jar (1712ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit/3.7.0.201502260915-r/org.eclipse.jgit-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit;3.7.0.201502260915-r!org.eclipse.jgit.jar (4558ms)
[info] downloading https://repo1.maven.org/maven2/org/eclipse/jgit/org.eclipse.jgit.ui/3.7.0.201502260915-r/org.eclipse.jgit.ui-3.7.0.201502260915-r.jar ...
[info] 	[SUCCESSFUL ] org.eclipse.jgit#org.eclipse.jgit.ui;3.7.0.201502260915-r!org.eclipse.jgit.ui.jar (5825ms)
[info] downloading https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.3.1/org.osgi.core-4.3.1.jar ...
[info] 	[SUCCESSFUL ] org.osgi#org.osgi.core;4.3.1!org.osgi.core.jar (7822ms)
[info] downloading https://repo1.maven.org/maven2/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar ...
[info] 	[SUCCESSFUL ] com.googlecode.javaewah#JavaEWAH;0.7.9!JavaEWAH.jar(bundle) (2609ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.3/httpclient-4.1.3.jar ...
[info] 	[SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.1.3!httpclient.jar (5658ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1.4/httpcore-4.1.4.jar ...
[info] 	[SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.1.4!httpcore.jar (1965ms)
[info] downloading https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar ...
[info] 	[SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (1307ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-container-default;1.0-alpha-9-stable-1!plexus-container-default.jar (2532ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.0.18/plexus-utils-3.0.18.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-utils;3.0.18!plexus-utils.jar (1572ms)
[info] downloading https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-io/2.2/plexus-io-2.2.jar ...
[info] 	[SUCCESSFUL ] org.codehaus.plexus#plexus-io;2.2!plexus-io.jar (381ms)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Exiting due to error in the template
File: /var/folders/c1/h2x2ptpd0y5fffkqn2k294zw0000gn/T/giter8-1487203219169165000/src/main/g8/build.sbt, context [anonymous] 9:14 internal error: org.stringtemplate.v4.compiler.STException: context [anonymous] 9:14 attribute name isn't defined
	at giter8.G8$STErrorHandler.runTimeError(g8.scala:110)
	at giter8.G8$STErrorHandler.runTimeError(g8.scala:105)
	at org.stringtemplate.v4.misc.ErrorManager.runTimeError(ErrorManager.java:133)
	at org.stringtemplate.v4.Interpreter._exec(Interpreter.java:193)
	at org.stringtemplate.v4.Interpreter.exec(Interpreter.java:145)
	at org.stringtemplate.v4.ST.write(ST.java:427)
	at org.stringtemplate.v4.ST.render(ST.java:497)
	at org.clapper.scalasti.ST.render(ST.scala:286)
	at giter8.G8$.applyTemplate(g8.scala:102)
	at giter8.G8$.write(g8.scala:154)
	at giter8.G8$.write(g8.scala:138)
	at giter8.G8$$anonfun$writeTemplates$2$$anonfun$apply$11.apply(g8.scala:396)
	at giter8.G8$$anonfun$writeTemplates$2$$anonfun$apply$11.apply(g8.scala:396)
	at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
	at scala.util.control.Exception$Catch$$anonfun$opt$1.apply(Exception.scala:118)
	at scala.util.control.Exception$Catch.apply(Exception.scala:102)
	at scala.util.control.Exception$Catch.opt(Exception.scala:118)
	at giter8.G8$$anonfun$writeTemplates$2.apply(g8.scala:395)
	at giter8.G8$$anonfun$writeTemplates$2.apply(g8.scala:386)
	at scala.collection.immutable.Stream.foreach(Stream.scala:547)
	at giter8.G8$.writeTemplates(g8.scala:386)
	at giter8.G8$$anonfun$applyT$1.apply(g8.scala:256)
	at giter8.G8$$anonfun$applyT$1.apply(g8.scala:249)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.G8$.applyT(g8.scala:249)
	at giter8.G8$.fromDirectory(g8.scala:62)
	at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:67)
	at giter8.JgitHelper$$anonfun$run$2.apply(JgitHelper.scala:66)
	at scala.util.Either$RightProjection.flatMap(Either.scala:523)
	at giter8.JgitHelper$.run(JgitHelper.scala:66)
	at giter8.JgitHelper$.run(JgitHelper.scala:78)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:34)
	at giter8.Giter8$$anonfun$2.apply(giter8.scala:33)
	at scala.Option.map(Option.scala:145)
	at giter8.Giter8.run(giter8.scala:33)
	at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.TemplateCommandUtil$.call(TemplateCommand.scala:68)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$runTemplate(TemplateCommand.scala:59)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:45)
	at sbt.TemplateCommandUtil$$anonfun$2.apply(TemplateCommand.scala:41)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:100)
	at scala.collection.immutable.List.find(List.scala:84)
	at sbt.TemplateCommandUtil$.sbt$TemplateCommandUtil$$run(TemplateCommand.scala:41)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:34)
	at sbt.TemplateCommandUtil$$anonfun$templateCommandParser$1.apply(TemplateCommand.scala:28)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by kpmeen** [comment]
I'm getting the same issue when running `sbt new akka/akka-scala-seed.g8`

**Comment by AntonioDrusin** [comment]
It is not picking up the properties. Quick workaround:
- install giter8:
http://www.foundweekends.org/giter8/setup.html
- run `g8 akka/akka-scala-seed.g8`
- use scala version 2.4.16 when asked

**Comment by ktoso** [comment]
@eed3si9n could this be an sbt bug?

**Comment by AntonioDrusin** [comment]
Just in case it helps. When getting the "name" attribute missing error i was using sbt 0.13.15
Also note that the defaults presented by g8 itself are empty
```
name []: a
akka_version []: 
```

**Comment by johanandren** [comment]
Still having this problem, just tried locally and no such problem.
